"""create application configuration table

Revision ID: 41fc37e0107d
Revises: bb43129b7a2b
Create Date: 2026-08-15 11:40:06.071314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fc37e0107d'
down_revision: Union[str, Sequence[str], None] = 'bb43129b7a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sla_warning_threshold_percent', sa.Integer(), nullable=False),
    sa.Column('escalation_check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('max_active_tickets_per_agent', sa.Integer(), nullable=False),
    sa.Column('allow_requester_reopen', sa.Boolean(), nullable=False),
    sa.Column('allow_admin_public_response', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('websocket_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_configs')
    # ### end Alembic commands ###
