"""create sla configs table

Revision ID: 668cb6914eab
Revises: c6ae705dff6b
Create Date: 2026-08-13 11:34:42.105687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668cb6914eab'
down_revision: Union[str, Sequence[str], None] = 'c6ae705dff6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_configs_id'), 'sla_configs', ['id'], unique=False)
    op.create_index(op.f('ix_sla_configs_priority'), 'sla_configs', ['priority'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_configs_priority'), table_name='sla_configs')
    op.drop_index(op.f('ix_sla_configs_id'), table_name='sla_configs')
    op.drop_table('sla_configs')
    # ### end Alembic commands ###
