"""create ticket audit table

Revision ID: 7cd86d77656f
Revises: 668cb6914eab
Create Date: 2026-08-14 21:07:28.352541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd86d77656f'
down_revision: Union[str, Sequence[str], None] = '668cb6914eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_audits_actor_id'), 'ticket_audits', ['actor_id'], unique=False)
    op.create_index(op.f('ix_ticket_audits_created_at'), 'ticket_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_audits_event_type'), 'ticket_audits', ['event_type'], unique=False)
    op.create_index(op.f('ix_ticket_audits_id'), 'ticket_audits', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_audits_is_internal'), 'ticket_audits', ['is_internal'], unique=False)
    op.create_index(op.f('ix_ticket_audits_ticket_id'), 'ticket_audits', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_audits_ticket_id'), table_name='ticket_audits')
    op.drop_index(op.f('ix_ticket_audits_is_internal'), table_name='ticket_audits')
    op.drop_index(op.f('ix_ticket_audits_id'), table_name='ticket_audits')
    op.drop_index(op.f('ix_ticket_audits_event_type'), table_name='ticket_audits')
    op.drop_index(op.f('ix_ticket_audits_created_at'), table_name='ticket_audits')
    op.drop_index(op.f('ix_ticket_audits_actor_id'), table_name='ticket_audits')
    op.drop_table('ticket_audits')
    # ### end Alembic commands ###
