"""create ticket responses table

Revision ID: c6ae705dff6b
Revises: 94c6505aa21b
Create Date: 2026-08-13 01:07:51.778016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ae705dff6b'
down_revision: Union[str, Sequence[str], None] = '94c6505aa21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_responses_author_id'), 'ticket_responses', ['author_id'], unique=False)
    op.create_index(op.f('ix_ticket_responses_created_at'), 'ticket_responses', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_responses_id'), 'ticket_responses', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_responses_is_internal'), 'ticket_responses', ['is_internal'], unique=False)
    op.create_index(op.f('ix_ticket_responses_ticket_id'), 'ticket_responses', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_responses_ticket_id'), table_name='ticket_responses')
    op.drop_index(op.f('ix_ticket_responses_is_internal'), table_name='ticket_responses')
    op.drop_index(op.f('ix_ticket_responses_id'), table_name='ticket_responses')
    op.drop_index(op.f('ix_ticket_responses_created_at'), table_name='ticket_responses')
    op.drop_index(op.f('ix_ticket_responses_author_id'), table_name='ticket_responses')
    op.drop_table('ticket_responses')
    # ### end Alembic commands ###
